apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: user16-app
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: backend
