apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

replicas:
- count: 1
  name: frontend

images:
- name: frontend-image

patches:
- path: resource-patch.yaml
  target:
    kind: Deployment
    name: frontend
- path: configmap-patch.yaml
  target:
    kind: ConfigMap
    name: frontend-config

configMapGenerator:
- name: frontend-config
  literals:
  - REACT_APP_API_BASE_URL=http://k8s-user16ap-backendi-e0f1b22e8d-1776638672.ap-northeast-2.elb.amazonaws.com
