apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

replicas:
- count: 1
  name: frontend

images:
- name: frontend-image
  newName: 833558168913.dkr.ecr.ap-northeast-2.amazonaws.com/user16/frontend
  newTag: 1.2.1

patches:
- path: resource-patch.yaml
  target:
    kind: Deployment
    name: frontend
