apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

replicas:
- count: 1
  name: frontend

images:
- name: 833558168913.dkr.ecr.ap-northeast-2.amazonaws.com/user16/frontend
  newName: 833558168913.dkr.ecr.ap-northeast-2.amazonaws.com/user16/frontend
  newTag: v1.2.0

resources:
- ../../base

patches:
- path: resource-patch.yaml
  target:
    kind: Deployment
    name: frontend
