apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: user16-app
spec:
  template:
    spec:
      containers:
      - name: frontend
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
